### Manage Pokemon Dataset

In [313]:
import pandas as pd

In [314]:
pkmn_dataset = pd.read_csv('csv/all_pkmn_data.csv', index_col=False)

In [315]:
pkmn_dataset

Name Pokedex_Number                    Type  \
0        Bulbasaur         #00001     ['Grass', 'Poison']   
1          Ivysaur         #00002     ['Grass', 'Poison']   
2         Venusaur         #00003     ['Grass', 'Poison']   
3       Charmander         #00004           ['Fire', nan]   
4       Charmeleon         #00005           ['Fire', nan]   
...            ...            ...                     ...   
1005  Iron Valiant          #1006   ['Fairy', 'Fighting']   
1006      Koraidon          #1007  ['Fighting', 'Dragon']   
1007      Miraidon          #1008  ['Electric', 'Dragon']   
1008  Walking Wake          #1009     ['Water', 'Dragon']   
1009   Iron Leaves          #1010    ['Grass', 'Psychic']   

                   Ability   Hp  Attack  Defense  Sp. Attack  Sp. Defense  \
0     Overgrow Chlorophyll   45      49       49          65           65   
1     Overgrow Chlorophyll   60      62       63          80           80   
2     Overgrow Chlorophyll   80      82       83         100          100   
3        Blaze Solar Power   39      52       43          60           50   
4        Blaze Solar Power   58      64       58          80           65   
...                    ...  ...     ...      ...         ...          ...   
1005           Quark Drive   74     130       90         120           60   
1006      Orichalcum Pulse  100     135      115          85          100   
1007         Hadron Engine  100      85      100         135          115   
1008        Protosynthesis   99      83       91         125           83   
1009           Quark Drive   90     130       88          70          108   

      Speed  
0        45  
1        60  
2        80  
3        65  
4        80  
...     ...  
1005    116  
1006    135  
1007    135  
1008    109  
1009    104  

[1010 rows x 10 columns]

In [316]:
pkmn_data_set = pkmn_dataset.rename(columns={'Sp. Attack' : 'Sp_Attack',
                                             'Sp. Defense' : 'Sp_Defense'})

In [317]:
pkmn_data_set.to_csv('csv/pkmn_dataset.csv', index=False)

In [318]:
pkmn_data_set = pkmn_data_set.set_index('Name')

In [319]:
pkmn_data_set

Pokedex_Number                    Type               Ability  \
Name                                                                        
Bulbasaur            #00001     ['Grass', 'Poison']  Overgrow Chlorophyll   
Ivysaur              #00002     ['Grass', 'Poison']  Overgrow Chlorophyll   
Venusaur             #00003     ['Grass', 'Poison']  Overgrow Chlorophyll   
Charmander           #00004           ['Fire', nan]     Blaze Solar Power   
Charmeleon           #00005           ['Fire', nan]     Blaze Solar Power   
...                     ...                     ...                   ...   
Iron Valiant          #1006   ['Fairy', 'Fighting']           Quark Drive   
Koraidon              #1007  ['Fighting', 'Dragon']      Orichalcum Pulse   
Miraidon              #1008  ['Electric', 'Dragon']         Hadron Engine   
Walking Wake          #1009     ['Water', 'Dragon']        Protosynthesis   
Iron Leaves           #1010    ['Grass', 'Psychic']           Quark Drive   

               Hp  Attack  Defense  Sp_Attack  Sp_Defense  Speed  
Name                                                              
Bulbasaur      45      49       49         65          65     45  
Ivysaur        60      62       63         80          80     60  
Venusaur       80      82       83        100         100     80  
Charmander     39      52       43         60          50     65  
Charmeleon     58      64       58         80          65     80  
...           ...     ...      ...        ...         ...    ...  
Iron Valiant   74     130       90        120          60    116  
Koraidon      100     135      115         85         100    135  
Miraidon      100      85      100        135         115    135  
Walking Wake   99      83       91        125          83    109  
Iron Leaves    90     130       88         70         108    104  

[1010 rows x 9 columns]

In [320]:
import numpy as np

In [321]:
pkmn_data_set.loc[:'Mew']

Pokedex_Number                  Type                 Ability   Hp  \
Name                                                                           
Bulbasaur          #00001   ['Grass', 'Poison']    Overgrow Chlorophyll   45   
Ivysaur            #00002   ['Grass', 'Poison']    Overgrow Chlorophyll   60   
Venusaur           #00003   ['Grass', 'Poison']    Overgrow Chlorophyll   80   
Charmander         #00004         ['Fire', nan]       Blaze Solar Power   39   
Charmeleon         #00005         ['Fire', nan]       Blaze Solar Power   58   
...                   ...                   ...                     ...  ...   
Dratini            #00147       ['Dragon', nan]  Shed Skin Marvel Scale   41   
Dragonair          #00148       ['Dragon', nan]  Shed Skin Marvel Scale   61   
Dragonite          #00149  ['Dragon', 'Flying']  Inner Focus Multiscale   91   
Mewtwo             #00150      ['Psychic', nan]        Pressure Unnerve  106   
Mew                #00151      ['Psychic', nan]             Synchronize  100   

            Attack  Defense  Sp_Attack  Sp_Defense  Speed  
Name                                                       
Bulbasaur       49       49         65          65     45  
Ivysaur         62       63         80          80     60  
Venusaur        82       83        100         100     80  
Charmander      52       43         60          50     65  
Charmeleon      64       58         80          65     80  
...            ...      ...        ...         ...    ...  
Dratini         64       45         50          50     50  
Dragonair       84       65         70          70     70  
Dragonite      134       95        100         100     80  
Mewtwo         110       90        154          90    130  
Mew            100      100        100         100    100  

[151 rows x 9 columns]

In [322]:
pkmn_data_set = pkmn_data_set.reset_index()

In [323]:
pkmn_data_set[(pkmn_data_set['Name'] == 'Mew')].index.to_list()

[150]

In [324]:
generations = [n for n in range(1, 10)]

def create_array(gen: int, limit: int) -> np.array:
    if gen > 9:
        return 'Invalid value'
    
    return np.array(
        [
            gen
            for _ in range(limit)
        ]  
    )

In [325]:
create_array(1, 151)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [326]:
create_array(2, 100)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [327]:
pkmn_data_set = pkmn_data_set.set_index('Name')

### Number of Gen 1 Pokemon

In [328]:
gen_1 = len(pkmn_data_set.loc[:'Mew'])

In [329]:
gen_1

151

### Number of Gen 2 Pokemon

In [330]:
gen_2 = len(pkmn_data_set.loc['Chikorita':'Celebi'])

In [331]:
gen_2

100

### Number of Gen 3 Pokemon

In [332]:
gen_3 = len(pkmn_data_set.loc['Treecko':'Deoxys'])

In [333]:
gen_3

135

### Number of Gen 4 Pokemon

In [334]:
gen_4 = len(pkmn_data_set.loc['Turtwig':'Snivy']) - 1

In [335]:
gen_4

108

### Number of Gen 5 Pokemon

In [336]:
gen_5 = len(pkmn_data_set.loc['Snivy':'Chespin']) - 1

In [337]:
gen_5

155

### Number of Gen 6 Pokemon

In [338]:
gen_6 = len(pkmn_data_set.loc['Chespin':'Rowlet']) - 1

In [339]:
gen_6

72

### Number of Gen 7 Pokemon

In [340]:
gen_7 = len(pkmn_data_set.loc['Rowlet':'Grookey']) - 1

In [341]:
gen_7

88

### Number of Gen 8 Pokemon

In [342]:
gen_8 = len(pkmn_data_set.loc['Grookey':'Sprigatito']) - 1

In [343]:
gen_8

96

### Number of Gen 9 Pokemon

In [344]:
gen_9 = len(pkmn_data_set.loc['Sprigatito':])

In [345]:
gen_9

105

### Total Number of Pokemons

In [346]:
sum([gen_1, gen_2, gen_3, gen_4, gen_5, gen_6, gen_7, gen_8, gen_9])

1010

In [347]:
gen_1, gen_2, gen_3, gen_4, gen_5, gen_6, gen_7, gen_8, gen_9

(151, 100, 135, 108, 155, 72, 88, 96, 105)

In [348]:
gen_col = pd.Series(
                [
                *create_array(1, 151), *create_array(2, 100), *create_array(3, 135), 
                *create_array(4, 108), *create_array(5, 155), *create_array(6, 72),
                *create_array(7, 88), *create_array(8, 96), *create_array(9, 105)
                ],
                name='Generation'
        )

In [349]:
gen_col

0       1
1       1
2       1
3       1
4       1
       ..
1005    9
1006    9
1007    9
1008    9
1009    9
Name: Generation, Length: 1010, dtype: int64

In [350]:
gen_col = gen_col.to_numpy()

In [351]:
gen_col

array([1, 1, 1, ..., 9, 9, 9])

In [352]:
new_pkmn_dataset = pkmn_data_set['Generation'] = gen_col

In [353]:
new_pkmn_dataset

array([1, 1, 1, ..., 9, 9, 9])

In [355]:
pkmn_data_set.loc['Treecko']

Pokedex_Number               #00252
Type                 ['Grass', nan]
Ability           Overgrow Unburden
Hp                               40
Attack                           45
Defense                          35
Sp_Attack                        65
Sp_Defense                       55
Speed                            70
Generation                        3
Name: Treecko, dtype: object

In [357]:
pkmn_data_set.to_csv('new_pkmn_dataset.csv')